### PR TITLE
[WIP] Implemented autoroll damage toggle

### PR DESCRIPTION
**Pull request by CarlosFdez**
EDIT: This has been sitting here a while and I use this module in games I play. So some commits have been added that go past the initial scope as nearly 2 weeks have passed. I can make a separate PR if you only want some of it.

Initial take on implementing an autoroll enable/disable feature. Please take a look over it and tell me what needs changing.

There are certain parts where I used JS features that are not commonly used in the codebase, and I also used the JSDoc function commenting convention (/**) on new functions for VSCode intellisense support. I can change that if need be.

Also note that the indices used for the damage roll are "snapshot" at the time of the attack roll. Perhaps a better way would be to snapshot the preset instead and have it look up the preset during the attack roll, but I noticed that brFlags are null on page reload. I haven't dug deep into it but it might be because of an optimization?

Localization entries are not implemented at all, the following will have to be added to every localization file including english: 
- br5e.autoRollDamage.name
- br5e.autoRollDamage.hint

For the config I chose to mean that true = default behavior. Most settings use positive verbiage and in general the trend seems to be that true = BetterRolls and false = default 5e, and autorolling damage is a BetterRolls thing.

Also as an aside (should maybe be a separate issue): I noticed that CustomRoll.eventToAdvantage() does not use the default foundry conventions. Currently shift is advantage whereas normally shift is neutral and alt is advantage. Is that discrepancy because of a Foundry update?

### CODE REVIEW

**Comment by CarlosFdez** [comment]
So after some trialing, its pretty close to a good solution, but its awkward for things with _only_ a damage roll (like sneak attack). I will need to make it always autoroll regardless of setting if there's no attack/saving throw component.

**Comment by CarlosFdez** [comment]
Actually, going to need an opinion @RedReign , should it be a single damage button that auto rolls the better rolls tab configuration (so regular/versatile + other all at once), or separate damage buttons for regular/versatile (grouped) + other?

**Comment by RedReign** [comment]
Hey, sorry about the lack of response!

I'm genuinely unsure what "autoroll damage" is supposed to accomplish, but perhaps I'm missing something. If you want damage automatically rolled on an item, you check that on the item's Quick Roll settings. Am I not understanding something here?

Also, the discrepancy for Adv/Disadv hot keys is because "Alt" is used for Alt Quick Rolls in Better Rolls. Wasn't sure of a better alternative but may come up with one soon.

**Comment by CarlosFdez** [comment]
Hey @RedReign , that's fine!

The goal was to implement this feature request that was made quite some time back, though I had to make a few guesses on what that would entail: https://github.com/RedReign/FoundryVTT-BetterRolls5e/issues/8

And you raise a good point regarding the alt key. Would have to think that for sure.

**Comment by RedReign** [comment]
TYVM for the pull requests! Your tab-switching fix has helped me immensely.
I have a slightly different idea for getting damage to roll after a prompt, which will require some experimentation. I will revisit this soon, though.

**Comment by CarlosFdez** [comment]
@RedReign No problem! I did the thing for my own purpose regardless and got some use out of it, and after having done it and using it in practice, I wouldn't go with this method. I was actually tempted on making a new module to allow ways of dynamically adding new rolls to things for things like hex or tensers and fixing the issues I had there.

So for martial characters, the current way works fine (with/without this PR). However for spells, it begins to fall apart. Here are two examples.
1) Scorching Ray - the same cast has multiple rolls. Currently in Better Rolls you have to cast it multiple times which is....very awkward. Even this PR doesn't fix that.
2) Certain spells have effects over multiple turns (Spirit Guardians). This is awkward even without better rolls but better rolls makes these cases much more complicated.

I was thinking of changing the behavior such that if something is a spell and autoroll damage is turned on, the spell description would have an Attack+Damage button that can be clicked multiple times. Autoroll turned off would make spells behave as if better rolls wasn't installed (separate attack/damage on the spell description).

**Comment by CarlosFdez** [comment]
As far as damage goes, using ChatMessage.update() to replace the damage button with the damage roll and create new dice is probably the best way to do.

As for the rest, I've thought of a way to deal with it for my goals but it would require a very large scope of changes. Rather than pushing a PR that changes...literally everything including the general flow, I'm taking a crack at writing a new smaller fork.

Closing the PR. Glad to see the tab fix has helped you! I got the idea for it from the Magic Items project.

**Comment by RedReign** [comment]
indeed! I am still referring to this fork for some guidance/ideas on how to approach a "roll prompt" feature I am developing as the "next big thing" for Better Rolls. Thanks for all the work you put into this, and I look forward to seeing what else you can come up with!

**Pull request closed without merging**
