### PR TITLE
Adds new utility functions to simplify the logic in custom-roll.js

### PR DESCRIPTION
**Pull request by Pjb518**
Adds five new utility functions to `utils.js`:

- `getActivationData`
- `getDuration`
- `getRange`
- `getSpellComponents`
- `getTarget`

Each of these replaces a complex series of nested conditional expressions, some of which were repeated in several places. Each of these instances have been replaced with a call to one of these new utility functions.

Please take extra care to test this particular set of updates, as the logic was very dense in some places, and despite my best efforts, there's always a chance the new functions don't perfectly replicate the original logic.

### CODE REVIEW

**Comment by CarlosFdez** [comment]
@Pjb518 so I'm actually tempted on doing something (I wasn't aware Red was willing on massive scope refactors), but I wanted to know your opinion on something so I don't clash with what you're doing.

What are your thoughts regarding moving anything regarding item data and property access, regardless of frequency of use, to utils? Example would be listProperties(), which is an item property at its core (In 5e vanilla its governed by `item.getChatData().properties`). Moving those to utils (scoped to item or otherwise) may not promote reusability, but they do promote single responsibility and encapsulation, and should make the code easier to get into for a new contributor since role logic isn't mixed up with item access as much.

If utils gets really big as a result, it should be possible to split them by data type to maintain readability.

**Comment by Pjb518** [comment]
I think those sound like very reasonable suggestions. My eventual goal regarding `utils.js` would be to turn `utils` into its own directory, and to have several different utility modules in there, so it sounds like we're thinking along the same lines. Even if we take a much lighter approach to moving things to `utils`, it's definitely going to end up very large, so having multiple utility files seems inevitable.

I also completely agree that a lot of the functions and modules are doing far too much, and it makes the whole thing very complicated. I want to extract what I can into much simpler functions, and I would like to see a bit of a reorganisation of the various module components as well.

At the moment, I'm still familiarising myself with the existing code, so I haven't made any particularly large changes so far. I've mostly been dealing with small style issues, and particularly complex bits of logic, like the conditional expressions in this PR. If you want to make some larger changes, I'd be very happy to combine efforts.

@RedReign has been very grateful for these small updates, so I'm sure a more substantial refactor would also be welcome if it makes the code easier to work with 🙂

**Comment by CarlosFdez** [comment]
Agreed fully with the util approach. That's a great way to do it. You can then namespace them based on thing they're affecting. I guess it makes sense to wait until the patterns start to show.

**Comment by CarlosFdez** [comment]
I refactored the chat button binding method so that its easier to add new functionality to it soon. Got something in mind for when this finishes.

**Comment by Pjb518** [comment]
Just added a **TODO** to `addButtonsToItemLi` to tidy up some of the logic, as it's currently a 240 line function with numerous switch cases full of additional conditional logic.

There are lots of obvious break points where we can split out this complex logic into smaller, simpler functions with more focused goals.

**Comment by Pjb518** [comment]
@CarlosFdez @RedReign 

What are your thoughts on using the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) and [logical nullish assignments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment)?

We currently have a bunch of lines like this:
```js
const activationCost = activation.cost ? activation.cost : ""
```
And this:
```js
if (item.data.flags.betterRolls5e === undefined) {
	item.data.flags.betterRolls5e = {};
}
```

Here are the same two blocks using these operators:
```js
const activationCost = activation.cost ?? ""
```
```js
item.data.flags.betterRolls5e ??= {};
```

**Comment by CarlosFdez** [comment]
The first one is equivalent to `const activationCost = activationCost || ";`. Without being certain about the underlying data, I think that would be the correct way to do it.

Wasn't aware the latter was an existing operator, Normally I do `thing.x = thing.x ?? default`. Good to know it exists.

**Comment by Pjb518** [comment]
Yeah, I actually picked a really bad example for the first one haha. There are cases where it might be `0` and we'd want to rule those out too, so `||` is definitely the right move there.

Given what you wrote in the second part of your comment though, it sounds like you'd be in favour of `??` in other cases where it actually does make sense.

**Comment by CarlosFdez** [comment]
Moved settings retrieval and initialization to a new settings class. Minor change in behavior, settings retrieval for rolls is dynamic rather than static (since now it uses get attribute access).

I'm somewhat tempted on merging hooks and any initialization in betterrolls5e.js to init.js (and rename init.js to index.js), however that is a much larger change. Should I handle that in the much deeper in scope one in #136 or should I do it here? Or not at all? I feel having one place that initializes things (that delegates to functions elsewhere) would solve some circular dependency issues as well as make it easier for contributors to trace logic.

**Comment by RedReign** [comment]
Excellent work, guys. So sorry it took so long to actually do anything about this. I've merged for now, and am going to try to work towards a fix, hopefully in the coming days.

**Pull request merged**
