### PR TITLE
Added Czech language

### PR DESCRIPTION
**Pull request by KarelZavicak**

### CODE REVIEW

**Comment by CarlosFdez** [comment]
Thanks for this! As a heads up, I recently did some new entries regarding damage buttons (quarter damage and temp hp application are now features). Let me know if you wanna add those in before I merge it in.

**Comment by KarelZavicak** [comment]
_"Replace {original} temporary health with {new} new temporary health?"_
strings in curly brackets are placeholders which gets replaced by values pasted in and thus should be kept intact or should I translate them as well?

**Comment by KarelZavicak** [comment]
Accomodated for recent changes.

**Comment by CarlosFdez** [comment]
Seems you figured it out. Yeah those are placeholders. Will merge, thanks for this.

**Pull request merged**
